### ISSUE TITLE
Outbound OAuth2 Authentication

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1136] opened 2024-06-08 00:17 UTC
# Story
As UCSD, so my EHR can receive results, I need ReportStream to be able to authenticate via OAuth2.

## Acceptance Criteria
- [x] We're able to authenticate to USCD's Epic environment using OAuth2.

###  Engineering
- [x] Research 
  - [x] Get familiar with RS's code base and how they generate JWTs
  - [x] Test how RS constructs the jwt
- [x] Changes to code base
  - [x] Discuss solutions
  - [x] Add jwtParams map to the RESTTransport constructor in TransportType.kt
  - [x] Extract map in getCredential in RESTTransport.kt
  - [x] Enhance lookupTwoLeggedCredential in RESTTransport.kt for use of jwtParams map to generate the jwt
  - [x] Refactor and final touches
  - [x] Update rest.md to include documentation for the new changes (`jwtParams`)
- [x] Unit test
 - [x] Test that jwt against EPIC's token endpoint to see if it is valid
~~Create How to onboard document~~ (moved to #1031)

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by basiliskus** [comment] 2024-06-14 17:10
It seems this will be more of an integration story with UCSD. As part of the work, we need to review the RS Programmer's Guide and make sure there are steps to set up outbound OAuth2 connection with RS

**Comment by saquino0827** [comment] 2024-06-21 16:52
Here's is the swagger doc for the description of [OAuth2](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/swagger.md) using Okta.

**Comment by jorg3lopez** [comment] 2024-06-21 18:16
We checked how RS builds the jwt that is used to request an access token, and it appears that it will work with their current setup. The one thing we need now is the endpoint where we will send the message to.

**Comment by jorg3lopez** [comment] 2024-06-24 15:58
Update:
We concluded that RS has the right setup for OAuth2 when they generate jwt. The jwt that is being generated is not valid when we hit the token endpoint. The problem is that the `issuer` and `subject` params are not the client id that we got from EPIC.  See picture:

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43344db248fcc2dfac75c67a6eff0ea3802c5167/image.png" alt="image.png" />

The other issue is that the audience is blank, instead of having the baseUrl that is used to retrieve the token. See picture:

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWlJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0b2802b038b8c2690d0cef17bf4b28e2e7aacfa/image.png" alt="image.png" />


Proposed solution:
I think that if we add these entries to the org file, we will have the ability to create JWTs with more flexibility and client customization.

**Comment by jorg3lopez** [comment] 2024-06-24 21:54
Currently, we have a draft [PR](https://github.com/CDCgov/prime-reportstream/pull/14869).

**Comment by jorg3lopez** [comment] 2024-07-10 05:03
Update: 
[PR ](https://github.com/CDCgov/prime-reportstream/pull/14869)has been merged!

**Comment by jorg3lopez** [comment] 2024-07-10 05:06
I suggest we move the `Create how to onboard document` to another ticket so we can close this one.

**Comment by JohnNKing** [comment] 2024-07-10 18:35
Need to overcome issue with HTTP 400 coming back from OAuth endpoint for UCSD

**Closed** 2024-07-24 18:44 UTC
Labels: story, California, Stream 2, result-to-hco, CA - Essential
