### ISSUE TITLE
LA Results LRIv5 Transformation

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1355] opened 2024-09-24 16:41 UTC
# Story
As Ochsner, so that our EHR can ingest results messages from ReportStream, I need all but one of the OBR segments removed.

## Pre-conditions
n/a

## Acceptance Criteria
- [x] The OBR for "54089-8" remains unchanged
- [x] All other OBR are removed from the outgoing HL7 ORU message
- [x] All OBXs appear under the sole remaining OBR
- [x] Numeric OBX IDs are sequential and unique
- [x] Write a RS E2E test that covers this transformation similar to #1255.

**See https://github.com/CDCgov/trusted-intermediary/issues/639 for the same effort that was done for CA.**

###  Engineering
- [x] Add draft transformations for this story (done before we had sample files)
- [x] Add unit tests for new transformation (done before we had sample files)
- [x] Use real sample files for unit tests
- [x] Make any necessary updates based on outcomes of sample files
- [x] Do manual E2E test with RS using sample files
- [x] Add RS E2E test that covers this transformation

## Definition of Done
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by saquino0827** [comment] 2024-10-03 20:40
Current outgoing questions: 
1) We have specific UCSD identifiers `R797`  and `R508`.  Are there identifiers we can leverage for LA?
2) Do we have up-to-date LA sample files?

**Comment by pluckyswan** [comment] 2024-10-03 21:42
[Branch](https://github.com/CDCgov/trusted-intermediary/tree/remove-la-obr-except-54089-8) for this

**Comment by saquino0827** [comment] 2024-10-07 20:51
Waiting for an answer for filtering for LA specific facilities.

**Comment by pluckyswan** [comment] 2024-10-08 20:56
We're currently filtering off:
> "Bundle.entry.resource.ofType(MessageHeader).destination.extension.where(url = 'https://reportstream.cdc.gov/fhir/StructureDefinition/universal-id').value = '1.2.840.114350.1.13.286.2.7.2.695071'"
We still **need** confirmation on final details for LA specific facilities and a LA sample ORU file, see thread for details: https://flexion.slack.com/archives/C044P2CBEKS/p1728057396567869.

**Comment by scleary1cs** [comment] 2024-10-09 16:23
[LA NBS MSH Values.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1kxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33fed586b14b3fc5992516b8c0b52210c0293980/LA%20NBS%20MSH%20Values.docx)

**Comment by scleary1cs** [comment] 2024-10-09 16:24
@saquino0827 @pluckyswan @jherrflexion above doc shared by Jason.

**Comment by saquino0827** [comment] 2024-10-09 16:36
Jason <jscott@jmichael-consulting.com> is working on getting an LA sample file for us.

Jason also confirmed that the MSH 5.2 OID is correct for filtering LA ORU specific messages.

**Comment by pluckyswan** [comment] 2024-10-25 15:59
See [here](https://flexion.slack.com/archives/C044P2CBEKS/p1729183359027129?thread_ts=1729094110.474449&cid=C044P2CBEKS) for sample files.

**Comment by saquino0827** [comment] 2024-10-31 19:57
We're waiting on a response from Jason to make sure the sample files don't contain PHI. We're set up with RS locally and will manually update the sample file for now to include test data

**Comment by saquino0827** [comment] 2024-11-01 19:50
We've scrubbed any potential PHI from the one sample file and ran it through the whole E2E Flow from RS -> TI -> RS; The end file seemed to be flattened correctly. However, before we commit test files to the repo and write E2E testing, we want to be sure the files do not contain PHI. We will follow up with Jason on Monday (11/04) during standup, if we do not get a response today.

**Comment by JScott-JMC** [comment] 2024-11-04 18:13
@somesylvie, we'll take this back to Lisa @ Natus.  All signs point to having her change this value to 54089-8 in her outputs.

**Comment by saquino0827** [comment] 2024-11-07 19:54
@JScott-JMC A follow-up on this, have we already schedule a talk or got a response back from Lisa? Double checking to make sure this 
question isn't forgotten.

**Comment by JScott-JMC** [comment] 2024-11-12 13:46
@saquino0827 we've confirmed with HCO & PHL that they will use the 54089-8 code for orders and results.  👍

**Comment by JScott-JMC** [comment] 2024-11-12 16:51
@scleary1cs did the Ochsner team send sample order messages per your request on Friday?
@somesylvie I'll be surprised if Ochsner updates their order code to 54089-8 in the near term.  We should be safe with a manual change for our testing in the meantime.
Also, Lisa couldn't confirm the PII question, so we should probably scramble the identifiable fields if we're posting to a public repository.

**Comment by scleary1cs** [comment] 2024-11-13 14:21
@JScott-JMC I have not seen any sample files yet, I'll follow up with an email to Mark and Paul right now.

**Comment by scleary1cs** [comment] 2024-11-13 21:05
MSH|^~\&|13^1.2.840.114350.1.13.286.2.7.2.695071^ISO|4169|Natus.LA.STAG^2.16.840.1.114222.4.3.26.3.2|Louisiana Office of Public Health Laboratory^2.16.840.1.114222.4.3.22.17.1.1|20241113131917|739|ORM^O01^ORM_O01|29|T|2.5.1|||AL|NE

PID|1|10453873^^^MRN^MRN|10453873^^^MRN^MRN||PKUSS^GIRL BEAKER||20241108103900|F||2054-5^Black or African-American^CDCREC|1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^P^^LAFAYETTE|LAFAYETTE|(557)559-5559^P^PH||ENGLISH|Single|||000-00-0000||PKUSS^BEAKER^MOM^|HISPANIC||Y|1|||||N

PD1||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI

NK1|1|PKUSS^BEAKER^MOM^|Mother|1202 Coolidge St.^^LAFAYETTE^LA^70503^US|(557)559-5559^^PH

PV1|1||^8288^24826^^^^^^^^||||||||||||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI

IN1|1|114420|308114401|BLUE CROSS BLUE SHIELD|P. O. BOX 98029^^BATON ROUGE^LA^70898-9029^||(800)495-2583|||||||||PKUSS^GIRL^BEAKER^|Self|20241108|1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^^^LAFAYETTE|||1||||||||||||||||||||None|F

GT1|1|100251815|PKUSS^BEAKER^MOM^||1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^^^LAFAYETTE|(557)559-5559^P^PH||19891224|F|P/F|MOT|999-99-9999||||||||Full

ORC|NW|243217771^EPC||71414746|||^^^20241113131800^^Routine^^||20241113131721|739^BEAKER^PHLEBOTOMIST^^||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|^^^^^^^^OLGH LABOR AND DELIVERY|(504)391-8896||||OCH155315^OCH155315|||OCHSNER LAFAYETTE GENERAL MEDICAL HOSPITAL^D^^^^OCHSNER HEALTH SYSTEM^XX^^^30100|1214 COOLIDGE BLVD^^LAFAYETTE^LA^70503-2621^US^B^^LAFAYETTE|(337)289-7991^^PH|120 OCHSNER BLVD^SUITE 360^GRETNA^LA^70056^^C|||||I|VERBAL WITH

OBR|1|243217771^EPC|1000319697^Beaker|54089-8^Newborn screening panel American Health Information Community (AHIC)^LN^^^^2.72||20241113131800|20241113131859|||739^BEAKER^PHLEBOTOMIST^^|Lab Collect|||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|(504)391-8896|||193989||||Lab|||^^^20241113131800^^Routine^^|||||||||20241113131800

OBX|1|ST|57714-8^Gestational Age (Weeks + Days)||384||||||F|||20241113131719|||||||||||||||QST

OBX|2|ST|82312-0^Infant Blood Transfusion?||No||||||F|||20241113131719|||||||||||||||QST

OBX|3|ST|67704-7^All Feeding Since Birth||Human Milk \T\ Formula||||||F|||20241113131719|||||||||||||||QST

OBX|4|ST|PLT3280^Name of Formula(s)||Enfomil, Similac, Katrina||||||F|||20241113131719|||||||||||||||QST

SPM|1|^24LADH-318X0008&Beaker||BLOOD^Blood||||BLOOD^Blood|||||||||20241113131859|20241113131900||Y|||||||||||||||S

**Comment by scleary1cs** [comment] 2024-11-13 21:06
MSH|^~\&|13^1.2.840.114350.1.13.286.2.7.2.695071^ISO|4169|Natus.LA.STAG^2.16.840.1.114222.4.3.26.3.2|Louisiana Office of Public Health Laboratory^2.16.840.1.114222.4.3.22.17.1.1|20241113131917|739|ORM^O01^ORM_O01|30|T|2.5.1|||AL|NE
PID|1|10453874^^^MRN^MRN|10453874^^^MRN^MRN||PKUSS^B BOY BEAKER||20241108110000|M||2054-5^Black or African-American^CDCREC|1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^P^^LAFAYETTE|LAFAYETTE|(557)559-5559^P^PH||ENGLISH|Single|||000-00-0000||PKUSS^BEAKER^MOM^|HISPANIC||Y|2|||||N
PD1||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI
NK1|1|PKUSS^BEAKER^MOM^|Mother|1202 Coolidge St.^^LAFAYETTE^LA^70503^US|(557)559-5559^^PH
PV1|1||^8288^24827^^^^^^^^||||||||||||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI
IN1|1|114415|308114401|BLUE CROSS BLUE SHIELD|P O BOX 98029^^BATON ROUGE^LA^70898-9029^||(800)495-2583|||||||||PKUSS^B^BOY BEAKER^|Self|20241108|1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^^^LAFAYETTE|||1||||||||||||||||||||None|M
GT1|1|100251816|PKUSS^BEAKER^MOM^||1202 COOLIDGE ST.^^LAFAYETTE^LA^70503^US^^^LAFAYETTE|(557)559-5559^P^PH||19891224|F|P/F|MOT|999-99-9999||||||||Full
ORC|NW|243217750^EPC||71414751|||^^^20241113125400^^Routine^^||20241113125406|739^BEAKER^PHLEBOTOMIST^^||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|^^^^^^^^OLGH LABOR AND DELIVERY|(504)391-8896||||OCH155315^OCH155315|||OCHSNER LAFAYETTE GENERAL MEDICAL HOSPITAL^D^^^^OCHSNER HEALTH SYSTEM^XX^^^30100|1214 COOLIDGE BLVD^^LAFAYETTE^LA^70503-2621^US^B^^LAFAYETTE|(337)289-7991^^PH|120 OCHSNER BLVD^SUITE 360^GRETNA^LA^70056^^C|||||I|VERBAL WITH
OBR|1|243217750^EPC|1000319696^Beaker|54089-8^Newborn screening panel American Health Information Community (AHIC)^LN^^^^2.72||20241113125400|20241113131841|||739^BEAKER^PHLEBOTOMIST^^|Lab Collect|||||1184608010^DREWITZ^TROY^U.^^^^^NPI^^^^NPI|(504)391-8896|||193988||||Lab|||^^^20241113125400^^Routine^^|||||||||20241113125400
OBX|1|ST|57714-8^Gestational Age (Weeks + Days)||382||||||F|||20241113125402|||||||||||||||QST
OBX|2|ST|82312-0^Infant Blood Transfusion?||Yes||||||F|||20241113125402|||||||||||||||QST
OBX|3|DT|62317-3^Date of Transfusion||20241108||||||F|||20241113125402|||||||||||||||QST
OBX|4|ST|67704-7^All Feeding Since Birth||Human Milk \T\ Formula||||||F|||20241113125402|||||||||||||||QST
OBX|5|ST|PLT3280^Name of Formula(s)||Enfomil||||||F|||20241113125402|||||||||||||||QST
SPM|1|^24LADH-318X0007&Beaker||BLOOD^Blood||||BLOOD^Blood|||||||||20241113131841|20241113131842||Y|||||||||||||||S

**Comment by scleary1cs** [comment] 2024-11-13 21:07
Sample files, also can be found in email(cdc-ti) copied subject "Sample order messages"

**Comment by JScott-JMC** [comment] 2024-11-14 16:40
They updated their LOINC!  NICE!!!

**Comment by saquino0827** [comment] 2024-11-14 22:05
I de-identified our LA sample ORU messages and put them in keybase for review the folder it's in is called `keybase://team/cdc_ti/de_identified_sample_files`. We need someone to review to make sure I properly de-identified them.

**Comment by saquino0827** [comment] 2024-12-02 22:36
I was able to manually test the LA de-identified sample files successfully. We worked on adding a new transformation rule as well and once the code is merged the RS e2e test should pass.

**Closed** 2024-12-11 19:36 UTC
Labels: story, Louisiana, Stream 1, transformation, LA - Essential

**Comment by scleary1cs** [comment] 2025-01-13 18:33
https://docs.google.com/spreadsheets/d/1DHMO0x8CzMwMgrz5C9T21kPGw-mcCm9r/edit?usp=drive_link&ouid=102849307490663018252&rtpof=true&sd=true

New LA Results Gap Analysis link.
